### ISSUE TITLE
Mocking base class methods doesn't work properly

### ISSUE THREAD

**Issue by alexjay** [krakjoe/uopz#10]
Hi!
It seems that it's impossible to mock base class method and get this method mocked in all derrived classes. Any workarounds?
Runkit is able to do such thing, btw.

**Comment by krakjoe** [comment]
Can you provide code, just so there is no confusion ?

**Comment by alexjay** [comment]
Yep, sure. Here are a couple of tests:
https://gist.github.com/alexjay/04476edf51d7c2a7d2b5
The second test mocks base class method and fails asserting that the method is mocked at a subclass.

**Comment by alexjay** [comment]
I've done some further reserch...
Base class methods mocking doesn't work only if these classes are in the same file as the test itself. If i place these classes in the separate files, mocking base class methods starts to work properly, but...

uopz_restore() makes weird things when mocking affects baseclass and its subclass, please take a look at these tests:
https://gist.github.com/alexjay/6474aa3db31fcfad5129

I've put tests in the separate files as they affects each other due to weird behavior of the uopz_restore() method.
These tests highlight two things:
1. If you try to restore subclass method that was derrived from the base one, it seems that this subclass will get it's own method copy and any further base class method mocking will no longer take affect. 
2. If you try to mock base class method and restore it then, it won't take affect on subclass, it will still has mocked method.

**Comment by alexjay** [comment]
Just to summarize...
It seems to me that after the first instantiation of a subclass any changes made to it's base class will no longer affect the subclass. This applies to uopz_restore/rename/delete/function at least.

**Comment by ksimka** [comment]
@krakjoe, any thoughts on this?

**Comment by antonvolkov** [comment]
Hi guys!

My problem looks similar
Take a look this gist: https://gist.github.com/antonvolkov/63d145589885bcb3b814
Works good with runkit
Any thoughts?

Thank you

**Comment by ksimka** [comment]
@antonvolkov Looks like our problem was that we didn't follow "uopz should be loaded before opcache" instruction. Check your ini.

**Comment by ksimka** [comment]
@antonvolkov sorry, we still have this problem too in general, but solved it by fixing tests :)

**Comment by tony2001** [comment]
runkit does this by going over all the children classes recursively and updating the method there.
I'm afraid there's no other way to fix this, other than this one.

**Comment by ksimka** [comment]
@tony2001 I believe with your experience you can fix it in minutes, Tony :) We will all be thankful.

**Comment by alexjay** [comment]
Uopz runs almost 20 times faster than runkit... so if that is the reason it's not worth fixing it at all :-)

**Comment by tony2001** [comment]
Well, to me "runs slow, but does what it's supposed to do" is better than "runs fast, but doesn't work", especially when talking about tests.
We're currently figuring out if we're ready to invest time into uopz. Runkit does its job for us mostly, but the recent lack of maintenance is definitely a bad indicator..

**Comment by krakjoe** [comment]
I'm aware of the fix, but not sure if I want to do that. We hadn't come across this yet because our use of autoloaders and setup and teardown results in sensible results.

I'd rather people done that, than complicate anything ... thoughts ?

**Comment by krakjoe** [comment]
So, I fixed it, so by default it will behave like runkit, but if you don't need that and find it to be too slow, change the last param to uopz_function to false.

If someone else could confirm it's fixed, that'd be great ...

**Comment by antonvolkov** [comment]
@krakjoe works fine for me now. thank you
