### ISSUE TITLE
Symfony options-resolver fails when ext-uopz is enabled

### ISSUE THREAD

**Issue by Niko9911** [krakjoe/uopz#101]
https://github.com/symfony/symfony/issues/29842

**Comment by krakjoe** [comment]
I'm able to reproduce the bus error with 5.1.0 and xdebug enabled as in your configuration ... I'm not able to reproduce with HEAD and xdebug enabled, so I think solved, but I'll leave this for you to close ...

**Comment by Niko9911** [comment]
Thanks @krakjoe! I will wait for new release and inform if this problem will continue!

I will close this issue when I can confirm latest version doesn't cause problems anymore.

**Comment by stof** [comment]
this might be the same than https://github.com/krakjoe/uopz/issues/98 btw.

**Comment by krakjoe** [comment]
It may be, but I couldn't reproduce the issue when the bug was posted, and when I asked the OP to try again, they said they couldn't compile and weren't using uopz anymore ... so I don't really know what to do with that ...

**Comment by krakjoe** [comment]
@stof are you able to produce anything like #98 ? 

It's highly likely to be fixed, 6.0.0 cuts interference with the engine a lot ... but if I can get a reproducing case and someone open to communication, I'm very happy to make sure ....

**Comment by croensch** [comment]
I can trigger it with:
```php
<?php
$c = 'Bogus';
$o = new stdClass;
echo ($o instanceof $c);
```
Fatal error does not happen with 5.0.2

**Comment by Niko9911** [comment]
@croensch That is highly possible. But can you reproduce it with 6.x?
As far I understand there is no sense to make fix for 5.x as 6.x is closing...

**Comment by krakjoe** [comment]
This is very frustrating, I'm not able to reproduce that bug with 7.2.13 and uopz v5.1.0 ... so I've nothing to compare it too ... I've tried with and without opcache, with and without xdebug, I've tried with and without zend mm, I've tried valgrind ... nothing ... I can't make a fault or memory error of any sort ...

Can you show me php -v output, are you on windows or a mac maybe ? Have you got any other particularly magical/non-standard extensions loaded ?

I'm stabbing in the dark ... thanks for taking the time though ...

**Comment by krakjoe** [comment]
Thankyou.

Can confirm that #98 is no longer an issue with 6.0.0

```
FROM amazonlinux:2

RUN amazon-linux-extras install epel
RUN amazon-linux-extras install php7.2=7.2.13
RUN yum install -y http://rpms.remirepo.net/enterprise/remi-release-7.rpm && \
    yum install -y yum-utils && \
    yum-config-manager --enable remi-safe
RUN yum install -y --enablerepo=remi-php72 php-mbstring php-pecl-libsodium
RUN yum install -y --enablerepo=remi-php72 php-devel
RUN yum install -y git build-essential gcc make
RUN git clone https://github.com/krakjoe/uopz && \
    cd uopz && \
    phpize && \
    ./configure && \
    make install

COPY bogus.php .

ENTRYPOINT ["php"]
CMD ["bogus.php"]
```

**Comment by krakjoe** [comment]
6.0.0 available in pecl and from remi, windows builds are still running, will appear [here](https://windows.php.net/downloads/pecl/releases/uopz/6.0.0/) before links on pecl ...

**Comment by krakjoe** [comment]
@Niko9911 are we done here ?

**Comment by Niko9911** [comment]
I Will check this today

**Comment by Niko9911** [comment]
I've tested all cases I had issues and some extra. Would consider as closed & fixed. Thanks!
