### ISSUE TITLE
Breaking and overlapping

### ISSUE THREAD

**Issue by krakjoe** [krakjoe/uopz#103]
It's been pointed out that there is a lot of overlap between componere and uopz, and this is causing confusion among users of both.

The overlap is coming from the fact that uopz_set_mock, which was originally just a replacement for test-helpers set_new_overload, has evolved into something that tries to implement the same sort of mocking that componere is better at, and without breaking the engine or overloading a bunch of it.

My intention is to revert the changes made since the last release, which will take uopz_set_mock back to the new overload with static method overload, then I want to remove the static overload so that uopz_set_mock behaves like the old test helpers function.

Those people that were using uopz_set_mock for more than that can look to componere and or mimus for more advanced mocking.

If there are no objections in the next 7 days or so, I'm going to go ahead and do it ... raise your hand if you object ...

**Comment by rlerdorf** [comment]
No objections from me.

**Comment by krakjoe** [comment]
Ok you should be good to go with d8ce60f39f44f51c6252d89149ac3ec3765b9afa, commented on older report also ...

If it LGTU it LGTM :)

Sorry about the wait ... wanted to give anyone a chance to object ...

**Comment by krakjoe** [comment]
Closing this now, I think resolved ...

**Comment by cmb69** [comment]
[Docs updated](http://svn.php.net/viewvc?view=revision&revision=346699); you may want to review.

And no need to apologize to me; I'm really happy that uopz is there, works with PHP 7.3, and frankly, I haven't even noticed that static member access would have been mocked as well.

**Comment by krakjoe** [comment]
Yeah, I think we done the right thing, even if it took a while to get there, and I much happier with the reduced complexity of uopz going forward also. Thanks for input @rlerdorf :)
