### ISSUE TITLE
Function uopz_allow_exit doesn't work when Xdebug is enabled

### ISSUE THREAD

**Issue by ABashkirtseva** [krakjoe/uopz#108]
Xdebug: 2.7.0
Uopz: 6.0.1
php: 7.1.23

I've written a small test:
````
<?php

uopz_allow_exit(false);

exit(1);
echo 1;

exit(2);
echo 2;

?>
````

Expected output
`12
`
Actual output is empty

But when I disable xdebug all works fine.

**Comment by krakjoe** [comment]
There is nothing I can do about that: Xdebug also overloads exit instructions and does not dispatch to any previously set handler.

**Comment by coolersport** [comment]
Use phpdbg. Just disable xdebug extension and run your test with:

    phpdbg -grr `which phpunit`

**Comment by cmb69** [comment]
It's `-qrr`, IIRC.

**Comment by krakjoe** [comment]
It is qrr ... although grr made me chuckle ...

Also, don't use phpdbg to run tests, use pcov for code coverage ... you
don't (shouldn't) need a debugger to run tests ...

xdebug and uopz are mutually exclusive in some respects and there is
nothing to do about that ...

Cheers
Joe
