### ISSUE TITLE
uopz_set_mock does not mock classes when xdebug is enabled

### ISSUE THREAD

**Issue by noldors** [krakjoe/uopz#110]
Hello, i am using uopz_set_mock for mocking some classes, but when xdebug is enabled it does not work as expected:

```php
class Foo {}

class Bar {}

uopz_set_mock(Foo::class, Bar::class);

var_dump(new Foo());
```

Without xdebug it output:

```
object(Bar)#6 (0) {
}
```

when xdebug is enabled it output:

```
class Foo#6 (0) {
}
```

Tested with uopz 6.0.0, 6.0.1 and 6.0.2-dev on php 7.1.28, 7.2.17 and 7.3.4

But if i install uopz 5.1.0 and enable xdebug it would work as expected.

Could you fix this?

**Comment by themech** [comment]
I'm having the same issues, with xdebug enabled `uopz_set_mock` does not work.

**Comment by rlerdorf** [comment]
@krakjoe @derickr have you looked at why this is?
It makes it impossible to do code coverage with xdebug if the tests you are analyzing use uopz for mocking.

**Comment by krakjoe** [comment]
xdebug doesn't save previously set opcode handlers when it installs handlers, so the uopz handlers are wiped out by xdebug, and since one is a php module and the other a zend extension, we can't enforce a load order ...

So I hacked around it and update the handlers in RINIT, that should do it ....

**Comment by rlerdorf** [comment]
Ah, nice one. This looks like it works for my simple tests so far. Thanks
