### ISSUE TITLE
Allow calling the original function on a uopz_set_return closure

### ISSUE THREAD

**Issue by ecommpro** [krakjoe/uopz#116]
I think one of the most interesting features of old version for PHP5 was the ability for rename a built-in function and, this way, create a wrapper in which we can call the original renamed function if necessary.

The only way I figure to achieve this on this version without modifying the functions table is having a reference to the original function in the closure passed to uopz_set_return when the flag execute is true.

Is there any way to achieve this?

**Comment by ecommpro** [comment]
For some reason, a call to the original function from the body of closure is not re-intercepted. That's exactly I was looking for.

If that's true and general, I think it would be great to add to the documentation in README.md file.

I'm closing the issue. Thanks, and great work.

**Comment by krakjoe** [comment]
That is intentional behaviour.

Thanks

**Comment by krakjoe** [comment]
Sorry I replied to wrong email ... It's hot :)

That is indeed intentional behaviour.

Thanks.

**Comment by cmb69** [comment]
That's already implicitely [documented via an example](https://www.php.net/manual/en/function.uopz-set-return.php#uopz-get-property.example.basic). I've [added a brief note](http://svn.php.net/viewvc?view=revision&revision=347805) to the function description now.
