### ISSUE TITLE
Release 6.1.1

### ISSUE THREAD

**Issue by remicollet** [krakjoe/uopz#119]
7.4.0 is RC, so with (hopefully) final API

develop branch have some fix for 7.4

@krakjoe time for a 6.1.1 ?

Also #110 for changelog ?

**Comment by krakjoe** [comment]
Hi @remicollet ... if you say it's time, it's time :)

#110 was closed by db01930f131eb5f673cba7bd536dab881818760c, changelog can be subject of issue, seems descriptive enough ?

**Comment by remicollet** [comment]
Tagged, released and announced

**Comment by krakjoe** [comment]
Thanks @remicollet
