### ISSUE TITLE
Unconditional exit code overloading

### ISSUE THREAD

**Issue by ksimka** [krakjoe/uopz#12]
This is just a @alexjay 's comment copy from #2 

----

I expiriencing the same trouble with uopz 2.0.6. Exit code spicified in exit() is missing.

How to reproduce:

enable uopz

```
zend_extension=uopz.so
```

create test.php file with exit

```php
<?php
exit(42);
```

run it

```
php test.php; echo $?
```

expected is 42
actual is 0

Exit code will be 0 regardless the value that was specified in the script.
I've tried to remove php_uopz_overload_exit at zend extension initialization and recomplie the uopz extension... and it helped. It seems that the default exit() uopz handler misses its exit code.

----

We simply removed `exit` overloading from uopz since we don't need it so far, but others can experience the same problem even not noticing it. So proper patch would be nice.

**Comment by krakjoe** [comment]
Fixed, there was a bug in exit overloading configuration.

**Comment by ksimka** [comment]
Awesome, thanks!
