### ISSUE TITLE
`uopz_set_return` prevents object destruction

### ISSUE THREAD

**Issue by JakeQZ** [krakjoe/uopz#121]
### Version Information

PHP 7.3.11 (cli) (built: Oct 22 2019 11:20:18) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Zend Engine v3.3.11
ext-uopz            6.1.1    The uopz PHP extension
(Windows 7 Home)

### Test Script

```php
<?php

class A
{
  public function __construct()
  {
    echo "A::__construct\n";
  }

  public function __destruct()
  {
    echo "A::__destruct\n";
  }

  public function foo()
  {
    return 'foo';
  }
}

function test()
{
  $a = new A();
  echo $a->foo() . "\n";
  $a = null;
  echo "done\n";
}

echo "test without `uopz_set_return()`\n";
test();

\uopz_set_return(A::class, 'foo', function() { return 'bar'; }, true);

echo "test with `uopz_set_return()`\n";
test();
```

### Expected Output

```out
test without `uopz_set_return()`
A::__construct
foo
A::__destruct
done
test with `uopz_set_return()`
A::__construct
bar
A::__destruct
done
```

### Actual Output

```out
test without `uopz_set_return()`
A::__construct
foo
A::__destruct
done
test with `uopz_set_return()`
A::__construct
bar
done
A::__destruct
```

### Notes

Although the destructor is called when PHP shuts down, it is not called when the only reference to the object is removed.  The existence of the UOPZ hook on the class shouldn't affect the behavior, but it does.

In a lengthy set of tests (or running some other complex tools) this can cause resources to become exhausted, if many (supposedly short-lived) instances of a class for which a method is hooked with `uopz_set_return()` are created over the lifetime of the test run.

I disabled non-default extensions like `opcache` and `xdebug` and got the same result.

I have not tested this with previous versions so have no idea if it is a long-standing or new issue.

**Comment by JakeQZ** [comment]
Calling `uopz_unset_return` also does not trigger the destructors to be called, though after this they will be called for new instances.

However, a workaround is possible (at least in the example case) by using `uopz_set_mock()` instead:

```php
class MockA extends A
{
  public function foo()
  {
    return 'bar';
  }
}

\uopz_set_mock(A::class, MockA::class);
```

This works even though the mock class extends the original class (and the destructors are called as expected) 🙂  Other classes that extend the original class will instead now extend the mock class, though obviously the mock class will not extend itself.

**Comment by cmb69** [comment]
It seems to me that `This` is not released, causing the leak.

**Comment by krakjoe** [comment]
This was fixed in a recent commit, and will be fixed in the next release.
