### ISSUE TITLE
Xdebug 2.9.3+ incompatibility

### ISSUE THREAD

**Issue by SMillerDev** [krakjoe/uopz#124]
When enabling UOPZ together with XDebug 2.9.3 or higher PHP execution will stall on any call on PHP 7.2 and 7.4. Let me know if you need any more info

**Comment by cmb69** [comment]
This has already been reported as issue #122.

**Comment by SMillerDev** [comment]
That didn't seem related judging by the title. I guess I learned a lesson about judging a book by it's cover again. Thanks @cmb69
