### ISSUE TITLE
PHP 8 compatible release

### ISSUE THREAD

**Issue by asprega** [krakjoe/uopz#143]
First of all, many thanks for this awesome extension.

I was trying to install this on php 8.0.3 using pecl, but installation fails (same error of previous issues):
https://github.com/krakjoe/uopz/issues/136
https://github.com/krakjoe/uopz/issues/135
https://github.com/krakjoe/uopz/issues/128

The last update was on Dec 2020, and it looked like @krakjoe was almost ready for a release. As nothing was released (still at 6.1.2), I thought I'd check with a new github issue (despite the duplicates above) to see if there have been any roadblock or a release is still planned.

Thanks again!

**Comment by westonNexben** [comment]
This is affecting my team as well.  Is it just a matter of pulling the trigger on a new release?

**Comment by krakjoe** [comment]
Will be fixed in #146
