### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by krakjoe** [krakjoe/uopz#146]
@remicollet when you have a moment, can you roll a release please ?

**Comment by remicollet** [comment]
ChangeLog

- Fix #145 uopz_find_hook segfault with PHP 8.0
- Fix #140 segfault with PHPUnit 9.5 caused by uopz_del_function

**Comment by remicollet** [comment]
Tagged and Released

**Comment by krakjoe** [comment]
Thanks remi, appreciated.

**Comment by westonNexben** [comment]
Thank you all!
