### ISSUE TITLE
zend_mm_heap corrupted

### ISSUE THREAD

**Issue by keywinf** [krakjoe/uopz#147]
I just updated uopz in my docker image with the last master commit e2b61ef0b532c3206af9e1931bc491be1cafd744

The very first unit test I tried to run immediately threw "zend_mm_heap corrupted"

Don't hesitate to ask for more details (phpunit version, etc.) if needed, if it's not immediate to solve it and it's worth it (I don't have a lot of time today for this).

**Comment by krakjoe** [comment]
Was this opened by mistake?

**Comment by keywinf** [comment]
No, I closed it because I thought the bug was related to other stuff, but re-open it because I was able to ensure the source of the problem was the last master commit indeed.

**Comment by keywinf** [comment]
I don't know if all's done now, but I tried the very last commit again (9e234607e892e8e218d4dfeffbf4a2417ae98e0e), and I still have the same problem

**Comment by krakjoe** [comment]
I've noticed my CI has gone to shit in the last few months because of travis changes.

It's passing now on travis, so you might try again ... or else I'll need a reproducing test case to investigate further.

**Comment by keywinf** [comment]
Still crashing. But I found that commenting my uopz_del_function lines could potentially "solve" the case. I'll come back to you with more details if you wish

**Comment by krakjoe** [comment]
@keywinf could you pull in latest source and do another test please ?

**Comment by keywinf** [comment]
Yes, I'll try that very soon

**Comment by keywinf** [comment]
Still the same problem, with a6cf9c635643509fb633da58009fe9f783af5d3f
