### ISSUE TITLE
appveyor

### ISSUE THREAD

**Issue by krakjoe** [krakjoe/uopz#148]
Hi Chrisoph,

Can you hook up appveyor with 8.0+ builds please ?

Thanks in advance.

**Comment by cmb69** [comment]
Would it be okay for you to switch to GH actions? Could use https://github.com/cmb69/setup-php-sdk, then.

**Comment by krakjoe** [comment]
That'd be fine, do I need to do anything ?

**Comment by cmb69** [comment]
Nope, that is enabled automatically. I'll provide a PR soonish.

**Comment by krakjoe** [comment]
Ta muchly, appreciated :)
