### ISSUE TITLE
uopz_extend

### ISSUE THREAD

**Issue by krakjoe** [krakjoe/uopz#152]
I'm not happy with this implementation, not really happy with the feature: We never used it, and I can't think of a time you would have to use it over returns or hooks.

I either want to delete these functions, or rewrite them ... I prefer to delete them.

Any objections to their removal ?

Context: In general, I'm trying to reduce surface area and improve testing so that uopz can be better maintained.

**Comment by rlerdorf** [comment]
No objections from me. I think it is a good idea to shrink things uopz touches and have never seen a case where `uopz_extend()` is used in the real world.

**Comment by krakjoe** [comment]
uopz_extend and uopz_implement have been removed from 7.1.0, thanks for input.
