### ISSUE TITLE
7.1.0

### ISSUE THREAD

**Issue by krakjoe** [krakjoe/uopz#154]
Hi remi,

Can we roll 7.1 release please ? 

Changes are mostly an internal rewrite of a bunch of stuff to improve stability and simplify, along with much improved CI.

uopz_implement and uopz_extend have been dropped.

I was hoping to make some progress on the 2 outstanding bugs, but a reproduce case doesn't look simple to create in either case. I think we've made a difference, but can't close them until I have a reproduce ...

**Comment by krakjoe** [comment]
I just squeezed in 34fbcd80e975103e92ac2ee2a74ac94092bce47d, can we make release inclusive of that ... sorry about last minute change.

**Comment by remicollet** [comment]
Tagged and announced.

**Comment by krakjoe** [comment]
Thanks muchly, appreciated :)

**Comment by cmb69** [comment]
Minimal docs for the function removal: https://github.com/php/doc-en/pull/836.

**Comment by krakjoe** [comment]
Thanks Christoph, more appreciation :)
