### ISSUE TITLE
error: implicit declaration of function 'RETURN_THROWS' is invalid in C99

### ISSUE THREAD

**Issue by calabashdoll** [krakjoe/uopz#156]
on mac
 cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/Users/didi/play/uopz -DPHP_ATOM_INC -I/Users/didi/play/uopz/include -I/Users/didi/play/uopz/main -I/Users/didi/play/uopz -I/Users/didi/play/output/php74/include/php -I/Users/didi/play/output/php74/include/php/main -I/Users/didi/play/output/php74/include/php/TSRM -I/Users/didi/play/output/php74/include/php/Zend -I/Users/didi/play/output/php74/include/php/ext -I/Users/didi/play/output/php74/include/php/ext/date/lib -I/Users/didi/play/uopz/. -DHAVE_CONFIG_H -g -O2 -c /Users/didi/play/uopz/uopz.c  -fno-common -DPIC -o .libs/uopz.o
/Users/didi/play/uopz/uopz.c:270:3: error: implicit declaration of function 'RETURN_THROWS' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                RETURN_THROWS();
                ^

**Comment by cmb69** [comment]
[uopz 7 is not compatible with PHP 7](https://pecl.php.net/package-changelog.php?package=uopz); use uopz 6 instead.
