### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by SeaSaltyCrackers** [krakjoe/uopz#161]
Can someone answer,what's problem?
/home/a/Desktop/uopz-5.1.0/src/copy.c: In function ‘uopz_copy_closure’:
/home/a/Desktop/uopz-5.1.0/src/copy.c:224:12: error: ‘zend_op_array’ {aka ‘struct _zend_op_array’} has no member named ‘run_time_cache’; did you mean ‘run_time_cache__ptr’?
  224 |  op_array->run_time_cache = zend_arena_alloc(&CG(arena), op_array->cache_size);
      |            ^~~~~~~~~~~~~~
      |            run_time_cache__ptr
make: *** [Makefile:195: src/copy.lo] Error 1

**Comment by SeaSaltyCrackers** [comment]
/home/a/FUGIO/Lib/uopz/src/util.c:90:21: error: ‘zend_class_entry’ {aka ‘struct _zend_class_entry’} has no member named ‘__serialize’; did you mean ‘serialize’?
   90 |     case 10: clazz->__serialize = function; break;
      |                     ^~~~~~~~~~~
      |                     serialize
/home/a/FUGIO/Lib/uopz/src/util.c:91:21: error: ‘zend_class_entry’ {aka ‘struct _zend_class_entry’} has no member named ‘__unserialize’; did you mean ‘unserialize’?
   91 |     case 11: clazz->__unserialize = function; break;
      |                     ^~~~~~~~~~~~~
      |                     unserialize
/home/a/FUGIO/Lib/uopz/src/util.c: In function ‘zif_uopz_call_user_func’:
/home/a/FUGIO/Lib/uopz/src/util.c:226:3: warning: implicit declaration of function ‘Z_PARAM_VARIADIC_WITH_NAMED’; did you mean ‘Z_PARAM_VARIADIC_EX’? [-Wimplicit-function-declaration]
  226 |   Z_PARAM_VARIADIC_WITH_NAMED(fci.params, fci.param_count, fci.named_params)
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |   Z_PARAM_VARIADIC_EX
/home/a/FUGIO/Lib/uopz/src/util.c:226:63: error: ‘zend_fcall_info’ {aka ‘struct _zend_fcall_info’} has no member named ‘named_params’
  226 |   Z_PARAM_VARIADIC_WITH_NAMED(fci.params, fci.param_count, fci.named_params)
      |                                                               ^
/home/a/FUGIO/Lib/uopz/src/util.c:226:77: error: expected ‘;’ before ‘}’ token
  226 |   Z_PARAM_VARIADIC_WITH_NAMED(fci.params, fci.param_count, fci.named_params)
      |                                                                             ^
      |                                                                             ;
/home/a/FUGIO/Lib/uopz/src/util.c: In function ‘zif_uopz_call_user_func_array’:
/home/a/FUGIO/Lib/uopz/src/util.c:253:5: error: ‘zend_fcall_info’ {aka ‘struct _zend_fcall_info’} has no member named ‘named_params’
  253 |  fci.named_params = params;
      |     ^
make: *** [Makefile:193: src/util.lo] Error 1

**Comment by cmb69** [comment]
Any particular reason why you want to build version 5.1.0? Which PHP version do you use?

**Comment by SeaSaltyCrackers** [comment]
I want to build version 7.4,the latter is a compilation error...

**Comment by SeaSaltyCrackers** [comment]
> Any particular reason why you want to build version 5.1.0? Which PHP version do you use?

I want to build version 7.4,the latter is a compilation error...

**Comment by cmb69** [comment]
According to the changelog, [support for PHP 7.4 is only available as of uopz 6.1.0](https://pecl.php.net/package-info.php?package=uopz&version=6.1.0). I suggest you try building uopz 6.1.2 for PHP 7.4.

**Comment by SeaSaltyCrackers** [comment]
> According to the changelog, [support for PHP 7.4 is only available as of uopz 6.1.0](https://pecl.php.net/package-info.php?package=uopz&version=6.1.0). I suggest you try building uopz 6.1.2 for PHP 7.4.
That's great, solved an afternoon's problem, thanks
