### ISSUE TITLE
PHP 8.2

### ISSUE THREAD

**Issue by DiffPetrovich** [krakjoe/uopz#170]
The uopz 7.1.1 PECL page says, that required PHP is 8.0.0 or newer. But I receive next message (Windows):

```
Warning: PHP Startup: uopz: Unable to initialize module
Module compiled with module API=20210902
PHP    compiled with module API=20220829
These options need to match
 in Unknown on line 0
PHP 8.2.4 (cli) (built: Mar 14 2023 17:54:25) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.2.4, Copyright (c) Zend Technologies
    with Xdebug v3.2.1, Copyright (c) 2002-2023, by Derick Rethans
```

Turning off Xdebug doesn't help.
Are there any plans for DLLs for PHP 8.2?

**Comment by macintoshplus** [comment]
I am pleased to announce that this extension is now compiled for Windows by the PHP Extension Repository site.

You can download the DLLs on the extension page: https://phpext.phptools.online/extension/php/uopz-231

If you have any questions, I am available to discuss them.

**Comment by cmb69** [comment]
Is this still unresolved? Maybe there have been new builds done in the meantime.

**Comment by cmb69** [comment]
> Maybe there have been new builds done in the meantime.

Indeed, there have been.
