### ISSUE TITLE
phpmd breaks once uopz.overload=1 is set

### ISSUE THREAD

**Issue by Vinai** [krakjoe/uopz#19]
If the uopz is installed and `uopz.overloads = 1` is configured, [phpmd](https://github.com/phpmd/phpmd) breaks:
```
[vinai@Sayyadina:/usr/local/etc/php/5.6/conf.d on master]
% cat ext-uopz.ini
[uopz]
zend_extension="/usr/local/opt/php56-uopz/uopz.so"
uopz.overloads = 1
[vinai@Sayyadina:/usr/local/etc/php/5.6/conf.d on master]
% php --version
PHP 5.6.9 (cli) (built: May 15 2015 09:36:14)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with uopz v2.0.7, Copyright (c) 2014, by Joe Watkins <krakjoe@php.net>
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.3.2, Copyright (c) 2002-2015, by Derick Rethans
[vinai@Sayyadina:/usr/local/etc/php/5.6/conf.d on master]
% phpmd --version                                                                                                                              127 ↵
PHPMD 2.2.2
PHP Fatal error:  Invalid opcode 65/4/8. in /usr/local/bin/phpmd on line 0
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/phpmd:0

Fatal error: Invalid opcode 65/4/8. in /usr/local/bin/phpmd on line 0

Call Stack:
    0.0003    2074240   1. {main}() /usr/local/bin/phpmd:0
```

Once `uopz.overloads` is not set (or the uopz extension is removed completely) phpmd works fine.
The same behavior can also be found in php 5.5.25.

Do you have any idea what in phpmd might cause this issue or how to work around it? I would really like to use both phpmd and uopz.overload in CI.

Since I don't know if this or phpmd is a better repository to report the issue I've cross posted here: https://github.com/phpmd/phpmd/issues/284

**Comment by diyism** [comment]
It seems uopz conflicts with php 5.4.42 when your php code contains "exit($var)", its exit() only accept constant string parameter.

**Comment by daniel-gomes-sociomantic** [comment]
I have the same problem when running `phpunit` tests with `uopz`.

Stats:
* Ubuntu 12.04.5 LTS
* PHP 5.5.29
* uopz v2.0.7
* PHPUnit 4.6.6 and 4.8.10

Any run of phpunit ends with:

    PHP Fatal error:  Invalid opcode 65/16/8. in phar:///usr/bin/phpunit/phpunit/TextUI/Command.php on line 0

And with exit code 255, even if all tests pass.

Disabling `uopz.overloads` or not loading `uopz` at all fixes the problem.

**Comment by daniel-gomes-sociomantic** [comment]
> It seems uopz conflicts with php 5.4.42 when your php code contains "exit($var)", its exit() only accept constant string parameter, or else: PHP Fatal error: Invalid opcode 65/16/8.

this is indeed the case (also for PHP 5.5.29), as can be seen in [PHPUnit's source code](https://github.com/sebastianbergmann/phpunit/blob/master/src/TextUI/Command.php#L170). 

If anyone reaches this with the same problem as me, I managed to fix this by editing PHPUnit's source, would be happy to share the fixed PHAR Archive. I know this is not a sustainable solution, but until `uopz` gets fixed I see no other way.

**Comment by AngeIII** [comment]
@daniel-gomes-sociomantic , what did you change in PHPUnit sources?

**Comment by daniel-gomes-sociomantic** [comment]
I simply replaced all `exit($var)` statements with `exit(n)` ones (where `n` is a constant value).

But an even better solution: get uopz's master branch and build it from there, the problem has been fixed on that branch at some point!

**Comment by krakjoe** [comment]
This is no longer a problem with v5.

**Comment by sadwxqezc** [comment]
I use 
    phpunit 4.8.35
    php 5.6.28
    uopz 2.0.4
It's ok
