### ISSUE TITLE
uopz doesn't work on Windows if a replaced function was called before from a function

### ISSUE THREAD

**Issue by peterholak** [krakjoe/uopz#27]
The following code that works perfectly fine on Linux (output should be a random byte in hex and then `ffffffff`) does not work on Windows (PHP 5.6.14, tried both x64 and x86, TS and NTS builds, enabled and disabled opcache, uopz binary 2.0.7 from https://pecl.php.net/package/uopz).

```php
<?php

function printRandomByte() {
    echo bin2hex(openssl_random_pseudo_bytes(1)) . "\n";
}

printRandomByte();
uopz_backup('openssl_random_pseudo_bytes');
uopz_function('openssl_random_pseudo_bytes', function($length, &$strong = null) {
    return hex2bin('ffffffff');
});
printRandomByte();
uopz_restore('openssl_random_pseudo_bytes');

```

It just outputs two random bytes instead (as if the `openssl_random_pseudo_byte` function wasn't replaced at all).

If I remove the first `printRandomByte()` call before the `uopz_backup`, then it works. If I remove the first call plus add a `printRandomByte()` call after the `uopz_restore`, PHP crashes.

If I replace the `printRandomByte();` calls with just the function body (`echo bin2hex(openssl_random_pseudo_bytes(1)) . "\n";`), then it works as it should.

It behaves similarly for other functions (I also tried `time()`)

**Comment by krakjoe** [comment]
Fixing this will be expensive ... it's assumed that you would replace functions before calling them ... I'm not sure it's worth fixing ... 

I'll think ...

**Comment by peterholak** [comment]
It's when running phpunit without the process isolation setting that other tests may call the function beforehand.

Anyway, if you decide not to fix it, it would be nice if it were mentioned in the documentation in some way.

**Comment by krakjoe** [comment]
So there's a fix for seven ... we loose caching, this will slow zend some, we might be able to be more selective about where caching is disabled, but I don't see a way right now ...

**Comment by AngeIII** [comment]
Also php error:PHP Fatal error:  Invalid opcode 65/16/8. 
if used like that:
```
$something = 'test';
die( $something );
```
= fatal

but :
```die( 'test' )``` = ok

**Comment by krakjoe** [comment]
This is not a problem any longer.
