### ISSUE TITLE
uopz breaks when xdebug is loaded

### ISSUE THREAD

**Issue by Sean-Der** [krakjoe/uopz#28]
Hey @krakjoe awesome extension, excited to start using it!

Currently it seems like xdebug breaks uopz when both are loaded (and load order doesn't matter) I didn't try a lot of stuff but the following exits with no output. (From the README)

```
<?php
uopz_overload(ZEND_EXIT, function($status = 0){});

class Test {
    public function method() {
        exit();
    }
}

class Unit {
    public function test() {
        $test = new Test();
        $test->method();

        return true;
    }
}
$unit = new Unit();
var_dump($unit->test());
uopz_overload(ZEND_EXIT, null);
var_dump($unit->test());
echo "failed";
?>
```

Is it possible to have two extensions in this area? (so I could submit a PR to xdebug/uopz) or do you know if the Zend VM was designed to only have one at a time. 

thanks

**Comment by krakjoe** [comment]
uopz is being reworked for seven, and stability ...

can I revisit this after I've done that ... we should be able to run with xdebug loaded, I hope ... but I'm not sure of the status of it right now ...

**Comment by Sean-Der** [comment]
Sounds perfect to me, thanks for the quick response @krakjoe ! I am lucky in my case I can disable xdebug while running unit tests

**Comment by krakjoe** [comment]
travis just went green on master (php7) branch ... dig away ... some of it had to be removed, documentation needs updating ... I'll get to it ... bottom of my list ...

I might sleep for 100 years, it's not evident in the commit history, but I've been at war with uopz for months ...

**Comment by kornrunner** [comment]
I can't reproduce this with current master branch

**Comment by krakjoe** [comment]
This is not a bug in uopz ... and I can't figure out what is wrong with xdebug, but with opcache disabled and no uopz loaded the following code has no output:

```
<?php
class Test {
    public function method() {
        exit();
    }
}

class Unit {
    public function test() {
        $test = new Test();
        $test->method();

        return true;
    }
}

$unit = new Unit();
var_dump($unit->test());

var_dump($unit->test());
echo "failed";
?>
```
