### ISSUE TITLE
module can not be loaded on Windows Bitnami WAMP stack

### ISSUE THREAD

**Issue by DanielRuf** [krakjoe/uopz#40]
I already tried to put `zend_extension=php_uopz.dll` before opcache and restarted the server but it always says `Failed loading C:/Bitnami/wampstack-5.6.16-0/php/ext\php_uopz.dll` but the file is there.

I tried `php_uopz-2.0.7-5.6-nts-vc11-x64` and `php_uopz-2.0.7-5.6-ts-vc11-x64` but still get the same error.

Is there something else we have to configure or change before this works? Any other requirements? Did someone else get it working under Windows?

**Comment by JL2014** [comment]
Try to install [Visual C++ Redistributable for Visual Studio 2012 Update 4 (x86 and x64)](http://www.microsoft.com/en-us/download/details.aspx?id=30679)

**Comment by DanielRuf** [comment]
Sorry for the late reply.

Microsoft Visual C++ 2012 Redistributable (86) version 11.0.61030 was already installed.

**Comment by Mugane** [comment]
Why is this closed without a solution?

**Comment by DanielRuf** [comment]
@Mugane I can not remmember as this was some years ago. I probably solved it by using the correct version for my PHP version back then.

My setup is completely different now.

Please open a new issue if you still have problems.

**Comment by cmb69** [comment]
> I tried php_uopz-2.0.7-5.6-nts-vc11-x64 and php_uopz-2.0.7-5.6-ts-vc11-x64 but still get the same error.

> Microsoft Visual C++ 2012 Redistributable (x86) version 11.0.61030 was already installed.

x64 and x86 have to match.

**Comment by DanielRuf** [comment]
> x64 and x86 have to match.

Right, I am not sure if and what versions where installed at this time as the VC Redist version mismatch and chaos (multiple different ones) makes it not easy.

I think I installed the 64 bit version on top of it and could solve it or had to change some other part.
For me this issue was solved so the comment does not help me anymore (after 4 years).

As already mentioned, others should open a new issue.

**Comment by Mugane** [comment]
Thanks for responding! I would agree, it should be separate. For me I
just won't use that dll. I wish there were a way to delete threads without
solutions, they seem to be a roadblocks.

**Comment by DanielRuf** [comment]
> I wish there were a way to delete threads without

Deletion is not a solution but owners and members (maintainers and collaborators) can lock issues as resolved. Issues should be only deleted if they contain spam or other unwanted content (eg security related).
