### ISSUE TITLE
Breaking PHPRedis connect

### ISSUE THREAD

**Issue by jnbdz** [krakjoe/uopz#41]
Hi,

I am simply trying to grab the params used in the method of the Redis class.

Here is my code:

```
        uopz_backup('Redis', 'connect');
        $redisConnect = uopz_copy('Redis', 'connect');

        uopz_function('Redis', 'connect', function($ip, $port, $timeout, $a, $b) use ($redisConnect)
        {
            var_dump('================================================');
            var_dump('================================================');
            var_dump('================================================');
            var_dump($ip);
            var_dump($port);
            var_dump($timeout);
            var_dump($redisConnect($ip, $port, $timeout, $a, $b));
            var_dump('================================================');
            var_dump('================================================');
            var_dump('================================================');

            return $redisConnect($ip, $port, $timeout, $a, $b);
        });
```

I tried this code without `uopz_backup` function. But it did not change anything.

Here is the first error I get. It seems it is the `uopz_copy` function that is throwing it.

`Warning: Cannot bind function Redis::connect to object of class Mindray_Core_Hooks`

The following error I get is this:

`Fatal error: Uncaught exception 'DataProvider_Exception' with message 'All servers timed out'`

So clearly using this code causes the PHPRedis to not connect. When I take out the code everything is fine. So it is this code that is the source of the problem.

What am I doing wrong?

Thanks in advance for any help.

**Comment by DanielRuf** [comment]
At the first look it seems the exception is not copied to the new function?

**Comment by jnbdz** [comment]
I have no idea. I am just trying to get the params sent to the methods/functions and what it is return if possible.

**Comment by krakjoe** [comment]
Closing because out of date API ... sorry I never got to it :)
