### ISSUE TITLE
uopz breaks zend.assertions setting

### ISSUE THREAD

**Issue by remicollet** [krakjoe/uopz#47]
Test script:

```
<?php
$testvar="a";
assert(is_bool($testvar), 'foo');
print "this is a test\n";
```

Without uopz

```
$ php -n -d zend.assertions=-1 foo.php 
this is a test
```

With uopz

```
$ php -n -d extension=uopz.so -d zend.assertions=-1 foo.php 
Warning: assert(): foo failed in /tmp/foo.php on line 5
this is a test
```

**Comment by krakjoe** [comment]
This is a bug in zend, we have to set compiler flags to stop it optimising special calls away, and with that zend disables it's special handling of the assert statement.

**Comment by krakjoe** [comment]
Fixed in php-src via http://git.php.net/?p=php-src.git;a=commit;h=34898e97663084c45b71385ef886e830e023da93 ... thanks @nikic
