### ISSUE TITLE
Problem with typehinted callable passed to uopz_add_function

### ISSUE THREAD

**Issue by vedadkajtaz** [krakjoe/uopz#54]
Hello,

The following code:

```
class	dbClass {}

class	testClass
{
	static private function	db() : dbClass
	{
		return new dbClass();
	}
}

uopz_add_function(testClass::class, 'phpunit_db', static function() : dbClass { return self::db(); }, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC);
$db = testClass::phpunit_db();

```
produces the following error:

> PHP Fatal error:  Uncaught TypeError: Return value of testClass::{closure}() must be an instance of , instance of dbClass returned in ...

Environment:

$ php -v
PHP 7.1.3 (cli) (built: Apr 11 2017 13:08:01) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.1, Copyright (c) 2002-2017, by Derick Rethans
    with Zend OPcache v7.1.3, Copyright (c) 1999-2017, by Zend Technologies

**Comment by krakjoe** [comment]
As far as I can tell, this was fixed at sometime in the past.

If the issue is reproducible without xdebug loaded, please re-open the issue.
