### ISSUE TITLE
call_user_func() ignores uopz_set_return hooks

### ISSUE THREAD

**Issue by cmb69** [krakjoe/uopz#55]
If a hook is set via `uopz_set_return()` it is called when the function is called directly or as variable function as desired. However, calling the function via `call_user_func()` circumvents the hook, and calls the original function instead.

Reproduce code:
````
function foo() {echo 1;}
uopz_set_return('foo', function () {echo 2;}, true);
foo(); // => 2 
$f = 'foo';
$f(); // => 2
call_user_func('foo'); // => 1
````

**Comment by krakjoe** [comment]
This was fixed at sometime in the past (when we added internal cuf/cufa overloads) ...

**Comment by cmb69** [comment]
Indeed, it works in current master. Sorry for the noise.
