### ISSUE TITLE
Request: Tagged release

### ISSUE THREAD

**Issue by SMillerDev** [krakjoe/uopz#58]
last release is quite a while back and isn't building against 7.1 for a lot of people.
A new "convenience release" as you called it for 5.0.1 would be much appreciated.

**Comment by SMillerDev** [comment]
@krakjoe would you be willing to tag a release?

**Comment by PeeHaa** [comment]
Can we have 7.1 and 7.2 pecl releases by any chance too @krakjoe? ❤️

**Comment by krakjoe** [comment]
@remicollet can you push out a release for 7 please ?

**Comment by jk** [comment]
@remicollet Any news on this?

**Comment by remicollet** [comment]
Sorry, I back from Holidays
You know, time totally "offline" ;)

@krakjoe I will take care of a new release ASAP.

**Comment by remicollet** [comment]
5.0.2 is released
