### ISSUE TITLE
uopz messing with exit;

### ISSUE THREAD

**Issue by rlerdorf** [krakjoe/uopz#65]
This cli script with uopz loaded:

```
<?php
echo 1;
echo 2;
echo 3;
exit(0);
echo 4;
echo 5;
echo 6;
```

will output: 123456

**Comment by kornrunner** [comment]
That's true if `uopz.overloads` is enabled in INI.

Can be disabled with `-duopz.disable=1`

**Comment by rlerdorf** [comment]
There is no `uopz.overloads` INI. Seems like a bug to override exit by default like that.

**Comment by rlerdorf** [comment]
I think the better answer here is to do call `uopz_allow_exit(true);` from a cli script running with uopz that needs to be able to exit

**Comment by rlerdorf** [comment]
And this patch switches the default:
```
diff --git a/uopz.c b/uopz.c
index f526c55..b37a5d1 100644
--- a/uopz.c
+++ b/uopz.c
@@ -61,6 +61,7 @@ PHP_INI_END()
 /* {{{ */
 static void php_uopz_init_globals(zend_uopz_globals *ng) {
        memset(ng, 0, sizeof(zend_uopz_globals));
+       UOPZ(exit) = 1;
 } /* }}} */
 
 /* {{{ PHP_MINIT_FUNCTION

**Comment by cmb69** [comment]
> There is no uopz.overloads INI.

But there was before uopz 5.0.0.
