### ISSUE TITLE
uopz_set_mock hangs when using an anonymous class as mock

### ISSUE THREAD

**Issue by mjec** [krakjoe/uopz#68]
When `uopz_set_mock` is called with an anonymous class as the mock, attempting to instantiate that class with an argument to the constructor causes the process to hang.

Minimal reproduction:

```php
<?php
class X {}
uopz_set_mock(X::class, new class { public function __construct() {} });
$x = new X(0);
```

Installation details:

```
$ php -v
PHP 7.1.10 (cli) (built: Oct 10 2017 16:51:19) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
with Zend OPcache v7.1.10, Copyright (c) 1999-2017, by Zend Technologies
with test_helpers v1.0.1-dev, Copyright (c) 2009-2013, by Johannes Schlueter, Scott MacVicar, Sebastian Bergmann
$ php --ri uopz

uopz

uopz support => enabled
Version => 5.0.2
```

I cannot reproduce this with xdebug on, but I assume that is actually just issue #61.

**Comment by mszabo-wikia** [comment]
uopz also hangs for me on PHP 7.2 when trying to set a PHPUnit mock object as the mock value, possibly it's the same issue. (PHP 7.0 is fine)
