### ISSUE TITLE
uopz_set_return() works with e.g. strlen() but not require_once() ?

### ISSUE THREAD

**Issue by simonhf** [krakjoe/uopz#70]
I'd like to track require and require_once usage in a larger PHP project which loads hundreds of PHP files. I came across uopz and installed it for PHP 7.1.1. I cobbled together an example script which seems to work fine for overriding strlen() using uopz_set_return(), but not when trying to override require_once(). Is this expected? Or how to override require_once()?

```
$ cat foo.php 
<?php

printf("foo.php: loaded\n");

uopz_set_return('strlen', function(string $string) : int {
        printf("- strlen(%s) via uopz_set_return()\n", $string);
        return strlen($string) * 2;
}, true);

$sl = strlen("abc");
printf("- debug: %u=strlen('abc')\n", $sl);

uopz_set_return('require_once', function(string $string) : int {
        printf("- require_once(%s) via uopz_set_return()\n", $string);
        return require_once($string);
}, true);

uopz_set_return('require', function(string $string) : int {
        printf("- require(%s) via uopz_set_return()\n", $string);
        return require($string);
}, true);

require_once "bar.php";

printf("foo.php: done\n");
```

```
$ cat bar.php 
<?php

printf("bar.php: loaded\n");

require_once 'zoo.php';

printf("bar.php: done\n");
```

```
$ cat zoo.php 
<?php

printf("zoo.php: loaded\n");

printf("zoo.php: done\n");
```

Here's the output of the script:

```
$ php foo.php 
foo.php: loaded
- strlen(abc) via uopz_set_return()
- debug: 6=strlen('abc')
bar.php: loaded
zoo.php: loaded
zoo.php: done
bar.php: done
foo.php: done
```

Seems to work just fine for overriding strlen() but has no affect on require_once(). Any ideas? Thanks!

**Comment by simonhf** [comment]
This [1] older apd doc comment says of a similar apd function called override_function(): "Please note that this function  will *not* override some important built-in "functions". Specifically, those which are actually statements/keywords, such as: require, include, require_once, include_once, echo, print"

So is this the same limitation for uopz? Or is there another way with uopz? And what makes these statements/keywords different from built-in functions?

[1] http://php.net/manual/en/function.override-function.php#114352

**Comment by mszabo-wikia** [comment]
`require_once`, `include`, `echo` and friends are not PHP functions, but statements.

**Comment by kornrunner** [comment]
Perhaps wrap `require_once` with some userland function, and then use `uopz`?

**Comment by cmb69** [comment]
As others have already pointed out, `require(_once)` is not a function, but rather a statement, and as such can't be mocked by uopz_set_return(). For similar reasons `exit` cannot be mocked either by uopz_set_return(), so that there is uopz_allow_exit() and uopz_get_exit_status().

> Perhaps wrap require_once with some userland function, and then use uopz?

That would be one possible solution. Another option would be to add a constant prefix to the require(_once) statements (declare the constant as empty string; mock with uopz_redefine()), and to [define a custom stream wrapper](http://php.net/manual/en/function.stream-wrapper-register.php).
