### ISSUE TITLE
Is uopz_set_property() supposed to create undefined properties?

### ISSUE THREAD

**Issue by cmb69** [krakjoe/uopz#82]
I've noticed that uopz_set_property() used on an instance is able to create a non-existing property (apparently with public visibility), but when used on a class, it does not. Is this expected behavior?

### Test script
````
class Foo {}
$foo = new Foo;
uopz_set_property($foo, 'bar', 1);
var_dump(uopz_get_property($foo, 'bar'));
var_dump($foo->bar);
uopz_set_property(Foo::class, 'baz', 2);
var_dump(uopz_get_property(Foo::class, 'baz'));
var_dump(Foo::$baz);
````
### Actual result
````
int(1)
int(1)
NULL
PHP Warning:  Uncaught Error: Access to undeclared static property: Foo::$baz in …
````

**Comment by krakjoe** [comment]
That's because of the way statics are allocated, we can't reallocate them at runtime, which adding a static property would require ...
