### ISSUE TITLE
call_user_func passes incorrect parameter to the function

### ISSUE THREAD

**Issue by vikramparth** [krakjoe/uopz#85]
After calling uopz_set_return, calling a function using call_user_func works incorrectly. Specifically, the parameter that gets passed to the function is incorrect. Instead of the actual parameter getting passed , the name of the function gets passed as the parameter. For e.g. - 

```
<?php
  
function myfunc($param)
{
    print $param . " world!\n";
}

$closure = function($param) {
    print $param . " universe!\n";
};

// replace myfunc
uopz_set_return("myfunc", $closure, true);

myfunc("hello");
call_user_func("myfunc", "hello");
```

Output - 

```
hello universe!
myfunc universe!
```

call_user_func_array doesn't have this problem (however, it calls the original function and not the replaced function. Is that expected?)

PHP version - 7.2.7
uopz version - 5.0.2

**Comment by krakjoe** [comment]
Sorry about the delay ...

**Comment by vikramparth** [comment]
Thank you for fixing this!
