### ISSUE TITLE
set_return and possibly other functions with traits and interfaces?

### ISSUE THREAD

**Issue by flavius** [krakjoe/uopz#86]
`uopz_set_return` and possibly the other functions do not work when catching executions for methods in traits (which are then used in classes).

Example:

```
<?php

trait Foo {
    public function emitEvent($data) {
        return $data+1;
    }
}

class Bar {
    use Foo;
}

$hook = function() {
    var_dump(__LINE__);
};

uopz_set_return(Foo::class, 'emitEvent', $hook, true);

$bar = new Bar;
$bar->emitEvent(1);

```

This works fine: `uopz_set_return(Bar::class, 'emitEvent', $hook, true);`.

I can imagine why this is (traits are just a copy/paste mechanism in the zend engine), but is it possible to make it work?

Similar situation with interfaces:

```
<?php

interface EventEmitter {
    public function emitEvent($data);
}


trait Foo {
    public function emitEvent($data) {
        return $data+1;
    }
}

class Bar implements EventEmitter {
    use Foo;
}

$hook = function() {
    var_dump(__LINE__);
};

uopz_set_return(EventEmitter::class, 'emitEvent', $hook, true);

$bar = new Bar;
$bar->emitEvent(1);
```

**Comment by krakjoe** [comment]
We could force it to work for traits, but it might get a bit messy, can you get by with interface support ?

**Comment by krakjoe** [comment]
I closed it when I added interface support, as that seems to solve your problem ...
